#!/usr/bin/env sh

mv ~/.bashrc ~/.bashrc.bak
mv ~/.bash_profile ~/.bash_profile.bak
mv ~/.gitconfig ~/.gitconfig.bak

ln -nfs ~/.dotfiles/bashrc ~/.bash_profile
ln -nfs ~/.dotfiles/bashrc ~/.bashrc
ln -nfs ~/.dotfiles/gitconfig ~/.gitconfig
#ln -nfs ~/Dropbox/bash/lib ~/lib

#ruby-rails
mv ~/.irbrc ~/.irbrc.bak
mv ~/.railsconsolerc ~/.railsconsolerc.bak
mv ~/.railsrc ~/.railsrc.bak
mv ~/.autotest ~/.railsrc.bak
mv ~/.rdebugrc  ~/.rdebugrc.bak
mv ~/.tmux.conf  ~/.tmux_conf.bak

ln -nfs ~/.dotfiles/irbrc ~/.irbrc
ln -nfs ~/.dotfiles/railsrc ~/.railsrc
ln -nfs ~/.dotfiles/railsconsolerc ~/.railsconsolerc
ln -nfs ~/.dotfiles/autotest ~/.autotest
ln -nfs ~/.dotfiles/rdebugrc ~/.rdebugrc
ln -nfs ~/.dotfiles/tmuxconf ~/.tmux.conf

#Install vim
mv ~/.vimrc ~/.vimrc.bak
mv ~/.gvimrc ~/.gvimrc.bak
mv ~/.vim ~/.vim.bak

ln -nfs ~/.dotfiles/vim/vimrc ~/.vimrc
ln -nfs ~/.dotfiles/vim/gvimrc ~/.gvimrc
ln -nfs ~/.dotfiles/vim/dot_vim ~/.vim