#!/usr/bin/env sh

if [ -f DOTFILE ]; then
  echo "DOTFILE exits" 
else
  echo "DOTFILE not exits"  
  echo "exec: rake install"  
  exit
fi

source DOTFILE  
echo $DOTFILE
mv ~/.bashrc ~/.bashrc.bak
mv ~/.bash_profile ~/.bash_profile.bak
mv ~/.gitconfig ~/.gitconfig.bak

ln -nfs $DOTFILE/DOTFILE ~/.DOTFILE   
ln -nfs $DOTFILE/bashrc ~/.bash_profile
ln -nfs $DOTFILE/bashrc ~/.bashrc
ln -nfs $DOTFILE/gitconfig ~/.gitconfig

#ruby-rails
mv ~/.irbrc ~/.irbrc.bak
mv ~/.railsconsolerc ~/.railsconsolerc.bak
mv ~/.railsrc ~/.railsrc.bak
mv ~/.autotest ~/.railsrc.bak
mv ~/.rdebugrc  ~/.rdebugrc.bak
mv ~/.tmux.conf  ~/.tmux_conf.bak

ln -nfs $DOTFILE/irbrc ~/.irbrc
ln -nfs $DOTFILE/railsrc ~/.railsrc
ln -nfs $DOTFILE/railsconsolerc ~/.railsconsolerc
ln -nfs $DOTFILE/autotest ~/.autotest
ln -nfs $DOTFILE/rdebugrc ~/.rdebugrc
ln -nfs $DOTFILE/tmuxconf ~/.tmux.conf

#Install vim
mv ~/.vimrc ~/.vimrc.bak
mv ~/.gvimrc ~/.gvimrc.bak
mv ~/.vim ~/.vim.bak

ln -nfs $DOTFILE/vim/vimrc ~/.vimrc
ln -nfs $DOTFILE/vim/gvimrc ~/.gvimrc
ln -nfs $DOTFILE/vim/dot_vim ~/.vim   

echo "fertig" 