#!/bin/sh
echo "Removing:"
for pattern in webrat-\* capybara-\* tmp/webrat-\* tmp/capybara-\* tmp/rtex/\* log/\* tmp/metric_fu\*
do
  echo "- $pattern"
  rm -fRv $pattern
done

echo "Finding recursively and removing:"
for pattern in \*~
do
  echo "- $pattern"
  find . -name $pattern -exec rm -v {} \;
done